### ISSUE TITLE
Developer documentation

### ISSUE THREAD

**Issue by ydennisy** [fluencelabs/fluence#103]
Hello,
When will you make dev docs available for writing to the network?
Thanks,
Dennis

**Comment by alari** [comment]
Hi @ydennisy !

We have some considerations which prevents us (yet) from releasing the Fluence test network. We're planning to fix a few issues before that, -- at least, make browser transport work.

Right now it's possible to use Fluence either from console interactive client, or via GRPC library in Scala.

Could you please describe your desired use-case? I'll ping you back as soon as Fluence is able to fit it.

Thanks!

**Comment by ydennisy** [comment]
Hello @alari , thanks for the reply.

I would like to use Fluence for storing decentralized identifiers https://w3c-ccg.github.io/did-spec/ 

Happy to use any method to interact with the test network but I could not find any docs.

Thanks!

**Comment by xdralex** [comment]
Now we do have the docs: https://fluence.network/docs/book/ :)
