### ISSUE TITLE
Adding module to dev node

### ISSUE THREAD

**Issue by VitaliiShpital** [fluencelabs/fluence#1038]
Hello!

I'm trying to figure out how fluence network works by adding some test module to dev node. After that I planned to try and call some simple functions from my module

I'm using simple react app where I bind next function to button click

```
import Fluence from "fluence";
import { peerIdToSeed, seedToPeerId } from "@fluencelabs/fluence";
import { dev } from '@fluencelabs/fluence-network-environment';
import { BASE64SERVICE } from "./artifacts/serviceBase64";

async function createFirstClient() {
   const SERVICE_NODE = dev[0];
   const pid = await Fluence.generatePeerId();
  
  let client
  try {
    client = await Fluence.connect(SERVICE_NODE.multiaddr, pid);
  } catch (e) {
    console.log(e.message)
  
    return
  }
  
  try {
    await client.addModule("basic", BASE64MODULE, undefined, undefined, 20000)
  } catch (e) {
    console.log(e.message)
  
    return
  }
}
```

I successfully connect to the node but adding module request always fails after 20 sec timeout

here's my console
```
Create waiting service 'addModule-e13ce959-2e2b-4111-ad8b-761206ab9a2a'
 inner interpreter outcome:
fluenceClient.ts:89 {ret_code: 0, error_message: "", data: Array(112337), next_peer_pks: Array(1)}

Timeout on waiting addModule-e13ce959-2e2b-4111-ad8b-761206ab9a2a
Particle with id dbc746bf-933e-4ebb-923d-9712131a162b deleted by timeout
```

What am I doing wrong? Can I add modules to dev nodes? Can I use React after all?

I tried to test my module with frepl and seems like everything works fine
my module consists of:
variable which is an empty vector of strings, 
push_to_vector(text: String)
get_vector() -> Vec<String>

Thank you in advance!

**Comment by folex** [comment]
Hi! Thanks for reaching out. Let's try to find and fix the problem :) 

I've searched through logs and haven't found particle `dbc746bf-933e-4ebb-923d-9712131a162b` unfortunately. What version of [fluence js sdk](https://www.npmjs.com/package/@fluencelabs/fluence) are you using?

And could you please switch to testnet? While currently `dev` is fine, it could be unstable in general.

Also, we have a tool for uploading modules & creating services – `@fluencelabs/fldist`. You can create a service using `fldist new_service` command.

**Comment by VitaliiShpital** [comment]
Thank you for the quick answer!

I've managed to deploy my simple service using fldist and successfully called my two methods from js.
I had to add config.json with a service name and use testNet instead of dev.

Now I'm testing aqua_demo trying to deploy user-list service which I believe already exists on test nodes. Can I redeploy them? Because trying to run this command 

`fldist new_service --modules user-list.wasm:config.json --name user-list`

gives me next response

```
argv.ttl: 60000 | as number + 1 : 60001
client seed: 2LymqT3dfxHjYYD1yjBQ9QDp9woxcQrAEyq5Kmx9aFFT
client peerId: 12D3KooWBdR6mS7zwiuK3HoMj4pK6M2hxvrzY5hKGKsrtNUP7oEC
node peerId: 12D3KooWBUJifCTgaxAUrcM9JysqCcS4CS8tiYH5hExbdWCAoNwb
uploading blueprint user-list to node 12D3KooWBUJifCTgaxAUrcM9JysqCcS4CS8tiYH5hExbdWCAoNwb via client 12D3KooWBdR6mS7zwiuK3HoMj4pK6M2hxvrzY5hKGKsrtNUP7oEC
creating service 04b288b2-907c-4a71-b3b1-98559fda5c85
Something went wrong!
Error: callback for _callback/createService timed out after 60000
    at Timeout._onTimeout (/Users/vitalii/.nvm/versions/node/v14.15.5/lib/node_modules/@fluencelabs/fldist/node_modules/@fluencelabs/fluence/dist/api.js:169:28)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

Thank you!

**Comment by folex** [comment]
user-list depends on sqlite3, so you have to create the service specifying both user-list and sqlite3:
```
fldist new_service --modules sqlite3.wasm:sqlite_config.json user-list.wasm:config.json --name user-list
```

order of the modules matters

**Comment by folex** [comment]
we'll improve the error message so it is doesn't timeout, but will show the actual error instead:
> Local service error: ret_code is 1, error message is '"Error: EngineError: trying to get imports from module with name sqlite3 that is not loaded"'

**Comment by folex** [comment]
https://github.com/fluencelabs/curl_template is a good starting point also

**Comment by VitaliiShpital** [comment]
Thank you so much!

**Comment by folex** [comment]
You can then test it via `run_air` in the following way (bash/zsh):
```bash
cat <<EOF > test.air
(xor
  (seq
    (call node (service "get_users") [] users)
    (call %init_peer_id% (returnService "run") [users])
  )
  (call %init_peer_id% (returnService "run") [%last_error%])
)
EOF

fldist run_air --log trace -p test.air -d '{"node": "12D3KooWBUJifCTgaxAUrcM9JysqCcS4CS8tiYH5hExbdWCAoNwb", "service": "cc867e16-31b8-4a0f-adb0-7c164be7b0e7"}'
```
