### ISSUE TITLE
it is possible to build distributed app?

### ISSUE THREAD

**Issue by crawter** [fluencelabs/fluence#1039]

**Comment by folex** [comment]
Sure it is! :) 

You can deploy your app's backend as wasm-based services, and manage replication through AIR script. Please check out **Developing apps and services** in docs at https://fluence.dev. [AIR reference](https://fluence.dev/docs/instructions) will also be of use!

Don't hesitate to ask more questions. BTW, we have discussions here on GitHub open, you might find it more approachable than issues! 😎 https://github.com/fluencelabs/fluence/discussions
