### ISSUE TITLE
allow to access particle remaining ttl in aqua

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/fluence#1183]
so that when users sends message, depending on ttl, he can choose how much to try to send that message to others

**Comment by dzmitry-lahoda** [comment]
for purposes of some changes of behavior of running particle and for collecting metrics

**Comment by dzmitry-lahoda** [comment]
so can build clever short circuit pattern. without ttl value cannot.

**Comment by folex** [comment]
It is now implemented in both aquavm ([#253](https://github.com/fluencelabs/aquavm/pull/253) [#256](https://github.com/fluencelabs/aquavm/pull/256/files)) and Aqua ([#505](https://github.com/fluencelabs/aqua/pull/505))
