### ISSUE TITLE
api about fluence node

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/fluence#1186]
Strange, auto test passed, but than stopped on krasnorad. I need more info to debug issue. How can i see (via Aqua) what version that node is, how long it is running without restarts?

**Comment by folex** [comment]
You can use [Peer.info](https://github.com/fluencelabs/aqua-lib/blob/main/builtin.aqua#L109) to get version information. Uptime info isn't available in builtins, unfortunately.

**Comment by dzmitry-lahoda** [comment]
hm, i do not see version field any were?

**Comment by folex** [comment]
it's there
