### ISSUE TITLE
fluence-fork-libp2p bad dependencies

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/fluence#1197]
https://crates.io/crates/fluence-fork-libp2p/0.36.2/dependencies

https://crates.io/crates/fluence-fork-libp2p-websocket/0.28.1/dependencies
https://crates.io/crates/soketto/0.4.2/dependencies

https://crates.io/crates/fluence-fork-libp2p-gossipsub/0.29.1/dependencies

see base64 0.12 and 0.13. 

this makes build of chef fail
```
INFO[1653] Running: [/bin/sh -c cargo chef cook --check --tests --all-targets --recipe-path recipe.json] 
error: failed to parse lock file at: /Cargo.lock
Caused by:
  package `base64` is specified twice in the lockfile
```

**Comment by folex** [comment]
@dzmitry-lahoda any updates? how to reproduce your problem?

**Comment by dzmitry-lahoda** [comment]
will share cargo chef example. but issue also in inability to use libp2p wasm in services.

**Comment by folex** [comment]
Please share a step-by-step instructions on how to reproduce the issue. I've no experience with `cargo chef`, but I've got experience debugging different Cargo issues. To be able to debug and diagnose, I need to be able to run it.

**Comment by folex** [comment]
not enough info
