### ISSUE TITLE
rtt to nodes in buildin

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/fluence#1221]
i see here is no rtt visible in api https://github.com/fluencelabs/fluence/blob/master/connection-pool/src/behaviour.rs . also i see some libp2p setup for ping. what is rule of removing from connected state? like RTT > 30 seconds? 

but it could be api feature to allow to decide protocols to route to closes nodes. when connected = false , than RTT = Infinity. 

But protocols can cap on 100ms, 1000ms, 10sec 100s sec RTTS to consider on its own what means connected.

**Comment by folex** [comment]
Does `Peer.timeout` solve this for you?

**Comment by folex** [comment]
no response
