### ISSUE TITLE
State machine documentation enhancement

### ISSUE THREAD

**Issue by DmiSergeev** [fluencelabs/fluence#151]
### Motivation
The current documentation is sometimes vague and not consistent:
* Some important procedures are not described.
* Some class descriptions contain forward references.
* When some statemachine functional moves to vm, add documentation described that.
* [ReadMe](../blob/master/statemachine/README.md) document is partly outdated and missing description of crucial parts of the state machine.

### Proposed change
* Remove forward references; segregate independent classes' scaladocs from examples of their usage.
* Bring ReadMe document up to date.
* Describe missing procedures, e. g. how to launch the local cluster and the client.

**Comment by alari** [comment]
Closed as obsolete
