### ISSUE TITLE
Rewrite State machine local cluster commands

### ISSUE THREAD

**Issue by DmiSergeev** [fluencelabs/fluence#153]
### Motivation
There is [a local cluster management scripts](../blob/master/statemachine/local-cluster-commands) to perform some actions with the local cluster like starting, stopping etc.

The current implementation doesn't follow the best practices of the process management. In particular, in [delete.sh](../blob/master/statemachine/local-cluster-commands/delete.sh):
* `kill -9` is used instead of more graceful process termination.
* Processes killed by grep pattern, it is dangerous because may kill more processes than required.

### Proposed change
* It would be better to store `pid`-s of the running processes in a dedicated file(s) and retrieve them from there to remove these processes only.
* Look up for other similar issues in other scripts and fix them.

**Comment by alari** [comment]
Closed as obsolete
