### ISSUE TITLE
Error hierarchy for State machine

### ISSUE THREAD

**Issue by DmiSergeev** [fluencelabs/fluence#155]
### Motivation
Currently, a significant amount of State machine code uses `String` as left part of `Either`/`EitherT` – for handling various errors and exceptional cases. It includes both creation of new error messages for some [edge cases](../blob/master/statemachine/src/main/scala/fluence/statemachine/state/TendermintStateHolder.scala#L54) and wrapping [caught exceptions](../blob/master/statemachine/src/main/scala/fluence/statemachine/tx/TxParser.scala#L46). It makes the current code not expressive enough and not clean.

### Proposition
A carefully designed error class/object hierarchy is required. [StateMachineError](../blob/master/statemachine/src/main/scala/fluence/statemachine/error/StateMachineError.scala) as the root class has already applied for the [transaction invocation](../blob/master/statemachine/src/main/scala/fluence/statemachine/tx/VmOperationInvoker.scala) and other statemachine part. VM project [error hierarchy](https://github.com/fluencelabs/fluence/issues/187) can be used as a reference.

**Comment by alari** [comment]
Closed as obsolete
