### ISSUE TITLE
Effecient merkelized tree for State machine

### ISSUE THREAD

**Issue by DmiSergeev** [fluencelabs/fluence#156]
### Motivation
Currently, a simple [unbalanced tree](../blob/master/statemachine/src/main/scala/fluence/statemachine/tree/TreeNode.scala) with lazy merkelizing is used. Such implementation might be enough for a prototype, but is not production-ready: this tree is not self-balancing and the number of node's children is not limited, so its performance may degrade easily.
We need to choose and implement an appropriate data structure.

### Proposed change
* Time/memory/size characteristics of typical operations (tree modification, traversal, Merkle proofs) should not degrade because under different workloads, in particular, it should be resistant to typical attacks against performance.
* Specifically, it should have `O(log N)` average-case complexity and the number of node's children should be constant (to avoid huge Merkle proofs).
* A good reference is Patricia tree, used in Ethereum: it is a binary trie structure with logarithmic asymptotics of basic tree operations.

**Comment by alari** [comment]
Closed as obsolete
