### ISSUE TITLE
Rewrite MerkleTreeNode merging rule

### ISSUE THREAD

**Issue by DmiSergeev** [fluencelabs/fluence#157]
### Motivation
Future work for a better merkelized storage is planned in #156. This is relatively large work. Before we do that we would still face problems with an existing implementation of [Merkle hash merging](../blob/master/statemachine/src/main/scala/fluence/statemachine/tree/MerkleHash.scala#L43):
* Two merging rules are provided, [one](../blob/master/statemachine/src/main/scala/fluence/statemachine/tree/MerkleHash.scala#L68) is mostly for debugging purposes.
* The current implementation is potentially vulnerable to 2nd preimage attack: different combinations of merging hashes produce the same digest function input. (While it is impossible for the current implementation because the lengths of the merged hashes are always the same, these lengths are not validated.)

These problems would not require huge efforts to resolve them so they might be resolved prior to #156.

### Proposed change
* To leave the only one merging rule.
* To rewrite hash merging either validating the lengths or prepending the hashes with the lengths, thus preventing the most straightforward 2nd preimage attack scenario.

**Comment by alari** [comment]
Closed as obsolete
