### ISSUE TITLE
Safe state switching in State machine

### ISSUE THREAD

**Issue by DmiSergeev** [fluencelabs/fluence#160]
### Motivation
Currently, there are race condition situations related to providing states to ABCI handlers.

In particular, there might be a situation when State machine provides an unverifiable state for Query requests:
* The State machine [Committer](../blob/master/statemachine/src/main/scala/fluence/statemachine/state/Committer.scala#L49) just finished Commit processing.
* But further processing of the response slows down or fails – in `jTendermint`, during delivery to Tendermint, or even inside Tendermint cluster.
* However, as soon as the processing in `Committer` finishes, this previous committed state becomes available to [QueryProcessor](../blob/master/statemachine/src/main/scala/fluence/statemachine/state/QueryProcessor.scala#L56) as Query state.
* Then the client cannot perform the whole verification because it cannot retrieve the header of this Query state block from Tendermint API.

Also, the current document lacks some important details regarding concurrency.

### Proposed change
The described and similar situation must be prevented:
* The straightforward way to do it is to provide such state to the Query request that is surely verifiable by the client – that is the state preceding the currently provided one.
* An alternative approach is to initially provide the same state as now but make it possible to fall back to the surely verifiable state in case the client cannot the verify initially provided one.

The implemented concurrency guarantees should be as clear as possible; the documentation should exhaustively describe any unclear concepts used.

**Comment by alari** [comment]
Closed as obsolete
