### ISSUE TITLE
State machine session data cleanup

### ISSUE THREAD

**Issue by DmiSergeev** [fluencelabs/fluence#168]
### Motivation
Currently, the State machine stores all the session metadata and results without any limits on the size of these data, leading to high storage usage – this may cause a performance degradation.

### Proposition
To implement automatic cleanup procedures in the State machine they must be triggered by client session termination (see #167).

Also this 'triggering' should ideally be tunable somehow, making it possible to define some 'period' (measured in time or number of transactions or blocks) when the cleanup is actually performed, possibly depending on how the termination occured (whether it was normally closed, failed, or expired).

Data that should be cleaned up [include](../blob/master/statemachine/src/main/scala/fluence/statemachine/tree/StorageKeys.scala):
* queued payloads
* statuses
* results of successful invocation and error messages
* client/session/tx hierarchy keys

**Comment by alari** [comment]
Closed as obsolete
