### ISSUE TITLE
Session/ordering attack protection

### ISSUE THREAD

**Issue by DmiSergeev** [fluencelabs/fluence#169]
### Motivation
In addition to lack of an implemented session data cleanup mechanism (#168) the current State machine sessions implementation is vulnerable to various attacks, for example:
* client generating too many sessions
* client sending too many transactions
* client causing queuing of too many transactions within a single session

Those attacks might be performed without significant attacker's efforts and would cause temporary or permanent Data engine unavailability. This makes some prevention measures against them obligatory.

### Proposed change
First, we need to identify major and secondary attack vectors to the sessions mechanism, in addition to those described in the motivation paragraph. 

Then, we need to specify some conditions and numbers that should be limited to prevent the identified attacks. Likely, it should include limitation on #sessions per client, #concurrent sessions per client, #txs per session, #queued txs per session, etc.

Finally, we need to implement those protection procedures. They are likely should be tunable (allowing to configure some limits and switch them on/off).

**Comment by alari** [comment]
Does it seem to be fixed?
