### ISSUE TITLE
Plans about a standard response format

### ISSUE THREAD

**Issue by macbem** [fluencelabs/fluence#189]
I've met Evgeny at a meetup in Warsaw and we've talked about the need of creating a standard response format so that you could pull data from multiple blockchains and expect similarly-shaped results for ease of development.

Are there any plans for that?

**Comment by xdralex** [comment]
Hey @macbem – we are working on the technical specification at the moment, and I guess the response format standardization might become a part of this. I would say there should be more details by the end of October :)
