### ISSUE TITLE
SBT 1.1.5+: lightbend config loading fails under `sbt run`

### ISSUE THREAD

**Issue by DmiSergeev** [fluencelabs/fluence#193]
### Motivation
Since SBT 1.1.5, lightbend-style config loading (used in [lightbend config](https://github.com/lightbend/config) and [pureconfig](https://github.com/pureconfig/pureconfig)) doesn't load configs from default Scala resource locations (`application.conf` and `reference.conf`) when the application launched via `sbt run`. It works, however, under Idea Run or under SBT 1.1.4.

As a temporarily solution to allow normal config loading SBT version is set to 1.1.4. However, it couldn't be a good long-term solution, disabling the access to new features and fixes in the newer SBT versions.

### Known details
The Scala-agnostic class loading and resource discovery (via `ClassLoader.getResource`) work for described locations under described SBT 1.1.5+. The problems begin in Scala-specific lightbend's `ConfigFactory.load`: those locations are not scanned during config loading.

It's known that SBT 1.1.5 and later versions use different temporary run directories and different base ClassLoader comparing with the 1.1.4 version.

### Proposition
To fix the problem or to find a workaround that allows both:
* flexible config loading from resource files
* running the project after the latest SBT versions

**Comment by alari** [comment]
Cannot reproduce now
