### ISSUE TITLE
A console utility for deploying code to cluster

### ISSUE THREAD

**Issue by DieMyst** [fluencelabs/fluence#269]
## Motivation
Current code deployment process to the Fluence network looks like this:
- Upload code to Swarm. Swarm will return the code hash.
- Publish the received hash to a default “deployer” contract.

If done manually this process is cumbersome, time-consuming, and error-prone.

## Proposition
Create an automation utility that will take the code as an input, go through the publishing process and return a hash of transaction of publishing to the developer, if successful.

**Comment by alari** [comment]
Shall it be closed with #273?
