### ISSUE TITLE
CORS error on workers

### ISSUE THREAD

**Issue by DieMyst** [fluencelabs/fluence#406]
Workers cannot accept requests from outside nodes. `cors_allowed_origins = ["*"]` parameter in `config.toml` presented and it worked before. 
Firstly, check if the generated config is used in workers.

**Comment by alari** [comment]
What version of Tendermint is affected? We have 2.7 in master now, and 2.9 in your branch.

**Comment by DieMyst** [comment]
It is fixed already in #417 
I will close the issue.
