### ISSUE TITLE
Show health/status of the app

### ISSUE THREAD

**Issue by folex** [fluencelabs/fluence#423]
Tendermint, node, workers status aggregated in a meaningful way. Should allow automatization of some devops tasks. #unclear

**Comment by alari** [comment]
Related to #671

**Comment by folex** [comment]
Do we need this? I think it's better to add such features to a web dashboard, cause there's not much CLI users

**Comment by folex** [comment]
There's already #671, I think there's not much new info in this (#423) issue, so I'd close it
