### ISSUE TITLE
Ethereum light nodes monitoring

### ISSUE THREAD

**Issue by folex** [fluencelabs/fluence#428]
Currently on Devnet with Kovan Parity light nodes it may happen that a light node sync wrong chain fork, and then hangs on syncing forever. After that, node's data should be deleted, and node should be restarted .

Periodically check that Ethereum light nodes are in the good fork (i.e., not in fork). This can be done by checking last block hash of each node and compare it to SOMETHING.

**Comment by alari** [comment]
Is it still an issue with our current Rinkeby setup?

**Comment by folex** [comment]
Nope, moving away from light nodes as of #670, and fullnodes are on check in Nagios.
