### ISSUE TITLE
Changeable logic for response querying

### ISSUE THREAD

**Issue by DieMyst** [fluencelabs/fluence#439]
- a client can customize the global timeout for the session
- exponential backoff on querying after some time 
- add some config for sessions

Querying - periodic check that Tendermint's response is formed

**Comment by folex** [comment]
@DieMyst This task was created a while ago, could you please check that this issue is still relevant, and maybe actualize its description? I remember we had a few thoughts about websocket transport, wouldn't it supersede this task?

**Comment by DieMyst** [comment]
This is relevant and is not superseded by web sockets. We will support the HTTP protocol as well. And cannot use only `push-from-server` model in web sockets. Querying result process should remain because of these reasons.

This issue is about: 
- not to DDOS Fluence nodes if there is a lot of requests
- stop querying if there is no response for some time
- additionally: add queue for querying responses

**Comment by folex** [comment]
Seems like this issue could be split into several separate issues.

> not to DDOS Fluence nodes if there is a lot of requests
1. An improvement in Fluence JS library - exponential backoff

> stop querying if there is no response for some time
Seems like it would be implemented in #638 

> additionally: add queue for querying responses
This is, too, an improvement in Fluence JS library? Or should that queue be on the Node/Statemachine side?

And original points:
> a client can customize the global timeout for the session
Is this about client giving up too early on transaction? Not sure what timeout is meant here

> add some config for sessions
Also not sure which config is meant here. Can you clarify, please?

**Comment by folex** [comment]
- Timeout & exponential backoff #678 
- Timeout from a 'server side' #638 
- Batch response querying #680 
- Queue/bounded parallelism #679 

Closing this as superseded by the above tasks.
