### ISSUE TITLE
Investigate statemachine WASM code compilation performance

### ISSUE THREAD

**Issue by michaelvoronov** [fluencelabs/fluence#446]
Time between wasm code loading and statemachine responding is too big (about a minute), need to investigate the cause of this performance degradation.

**Comment by folex** [comment]
After statemachine refactoring, its startup now faster, but it still requires unexpected amount of time to compile and load WASM code in Worker.

**Comment by michaelvoronov** [comment]
With Wasmer this issue isn't relevant.
