### ISSUE TITLE
Periodically remove apps deployed on devnet

### ISSUE THREAD

**Issue by folex** [fluencelabs/fluence#465]
Nodes preallocate a range of ports and register that range within smart contract. On devnet, when users deploy new apps on Fluence-hosted nodes, port range can be exhausted quite quickly, so some freeing strategy should be employed. 

One such strategy is to periodically clean deployed apps from contract using owner account. App should be removed if it was deployed more than N minutes (presumably 60 minutes). 

This way, users can use Fluence-hosted nodes to try Fluence, go through [Quickstart guide](docs/kickstart.md), and such. After user finish, logic described above would remove their app, and free used resources, so other users can do the same.

**Comment by alari** [comment]
We decided to apply #485 instead.

Clean up logic should be applied anyway, will do in separate ticket later.
