### ISSUE TITLE
Update Node.lastPort in contract when worker using largest port is deleted

### ISSUE THREAD

**Issue by folex** [fluencelabs/fluence#466]
As described in #465, resources should be freed up periodically. In order to keep smart contract's logic simple, and because it's a devnet-specific issue, it makes sense to implement "freeing" logic outside of smart contract.

The following algorithm should be implemented in node:
1. On start, listen for `NewNode` event for current node, and retrieve `Node` from smart contract via `Network.getNode` method
2. Implement `Deployer.setLastPort(K)` in smart contract, where `K` is a port number.
    It should set `Node.lastPort` to specified value. It should only affect "free" ports. i.e., given there exists an app running on port `N`, it should only be possible to set `lastPort` to `K > N`.  For `K <= N`, `setLastPort(K)` should revert.
3. Node should keep track of its apps, and when an app on port `node.lastPort - 1` is deleted, node should call `Deployer.setLastPort` for all contiguous free ports.

**Comment by alari** [comment]
We decided to apply #485 instead.
