### ISSUE TITLE
Integrate CircleCI

### ISSUE THREAD

**Issue by folex** [fluencelabs/fluence#471]
Currently we're using TravisCI. It's a bit too slow, and hard to get right. Let's try CircleCI, it looks so much faster on a first try.

[Here's my first try with CircleCI](https://github.com/folex/fluence/blob/master/.circleci/config.yml)

[And the same, but with specific commmit](https://github.com/folex/fluence/blob/3c0ed1a44ebf7c0b32b228cafca8fa75d02e3b7d/.circleci/config.yml)

Out-of-the-box it supports Scala, Rust and Node. It even has containers Scala+Node and Rust+Node. But integration tests require Scala + Rust + Node, it would require a custom container.

**Comment by alari** [comment]
Does it seem to be fixed?
