### ISSUE TITLE
Devnet health monitoring & alerts

### ISSUE THREAD

**Issue by folex** [fluencelabs/fluence#472]
Our core services are Parity, Swarm, Node, Worker and Tendermint.

Their health should be monitoring, with alerting to Slack.

All health checks should be documented.

Since there's already a Netdata (#420), a few [custom Netdata plugins](https://docs.netdata.cloud/collectors/plugins.d/#writing-plugins-properly) (scripts) written in Python, Go or Bash could be a good solution.

**Comment by alari** [comment]
Does it seem to be fixed?
