### ISSUE TITLE
Reorganize enqueuedApps to avoid out-of-gas

### ISSUE THREAD

**Issue by alari** [fluencelabs/fluence#489]
Currently it's possible to produce deadlock in Fluence Smart Contract with sending lots of transactions to enqueue apps for deployment, with huge requested cluster size. In this case, every next transaction will be forced to iterate through enqueuedApps, looking for an app to deploy, with no result except gas consumption.

We should reorganize enqueuedApps to be a mapping like `uint expectedClusterSize => array of enqueued apps`, to iterate only through the apps which could possibly fit in size.

**Comment by folex** [comment]
Should it be in the mp1 milestone? Or is it ok to move it to mp2, and live with current contract impl until significant portion of contract's logic moves to Kademlia ?
