### ISSUE TITLE
Node stops accepting events after a while

### ISSUE THREAD

**Issue by DieMyst** [fluencelabs/fluence#569]
One of the solutions: periodically reconnect master node with ethereum node and pull data from smart contract

**Comment by alari** [comment]
Does it seem to be fixed?

**Comment by folex** [comment]
Not really, we need more time to gather data about that

**Comment by alari** [comment]
Let's take another look once #667 is fixed.

**Comment by DieMyst** [comment]
Is it relevant? Or has it already been fixed with a reconnect and multiple ethereum nodes with the balancer?

**Comment by folex** [comment]
I haven't seen this happening for a long time. Let's close it and reopen if the bug is detected again.
