### ISSUE TITLE
Dockerize the Runner

### ISSUE THREAD

**Issue by alari** [fluencelabs/fluence#620]
Currently, to develop WASM programs without deploying them to Fluence we use dedicated Scala Runners. It puts a lot of unnecessary burden on developers.

Let's dockerize the runner to simplify the workflow.

**Comment by alari** [comment]
@folex update on the status of this issue, please?
What else should be done? Perhaps documentation?

**Comment by folex** [comment]
This one is completed, better docs would be a part of #637
