### ISSUE TITLE
Websocket interface 

### ISSUE THREAD

**Issue by folex** [fluencelabs/fluence#633]
## Current state
Currently, HTTP communication with a Fluence app is as follows:
1. Send transaction 
2. Poll for a result (until transaction is processed)

## Motivation
Current implementation requires a lot of network interactions between client and a Fluence app, and it could easily overwhelm the browser. 

A better approach would be to keep a persistent websocket connection between a web app and Fluence, and when a result is ready, worker would push that result into the websocket connection. 

It would also allow a backend on Fluence to generate some events, that should be pushed to all connected clients without explicit request. Akin to SSE or events in Ethereum.

**Comment by DieMyst** [comment]
fixed in #831
