### ISSUE TITLE
Documentation for debugging backends with 'runner'

### ISSUE THREAD

**Issue by folex** [fluencelabs/fluence#637]
Successor of #620

Current [README](https://github.com/fluencelabs/fluence/blob/master/vm/flrun/README.md) lacks details, and doesn't describe workflow in full. 

As it is an important part of developer's flow, it should be described in docs.

**Comment by alari** [comment]
Actual documentation is at https://fluence-labs.readme.io/docs/debugging

**Comment by folex** [comment]
Should we consider this issue fixed? Seems like documentation covers crucial parts, though obviously would benefit from improvements.
