### ISSUE TITLE
Redis fluencentization

### ISSUE THREAD

**Issue by michaelvoronov** [fluencelabs/fluence#647]
It is needed to port [Redis](https://github.com/antirez/redis) on Fluence.

**Comment by DieMyst** [comment]
Is this task already completed?

**Comment by michaelvoronov** [comment]
The initial version of Redis has been fluencentized. Could be found [here](https://github.com/fluencelabs/redis/tree/wasm). At now it is 5.0.3 version of Redis without pubsub, modules, cluster and replication API.
