### ISSUE TITLE
Investigate unexpected hang out of wasm-ld

### ISSUE THREAD

**Issue by michaelvoronov** [fluencelabs/fluence#649]
wasm-ld from [wasi-sdk](https://github.com/CraneStation/wasi-sdk) hangs out while linking on some setups.

Initially submitted [here](https://github.com/fluencelabs/tutorials/issues/2).

**Comment by michaelvoronov** [comment]
<img width="1133" alt="Screen Shot 2019-04-19 at 20 49 02" src="https://user-images.githubusercontent.com/11981714/56436474-a877cd80-62e4-11e9-9119-7e651ff5b232.png">

From here it could be seen that it is really a hang out.

**Comment by michaelvoronov** [comment]
The main problem is that this hang out is reproduced not on all setups (software+hardware) - at now I can reproduce it on Redis building only on VPS with Ubuntu 18.04, 2 * 2 GHz, 4Gb RAM. [Hello world](https://github.com/fluencelabs/tutorials/tree/master/hello-world/app-logger-c) could be compiled on every setup available to me (with and without docker on MacOS/Ubuntu/Debian). But [there](https://github.com/fluencelabs/tutorials/issues/2) it happened on our hello-world example. 

Also, it seems that options like `--export` and `--strip-all` affect this hang out. And `-thinlto-jobs=1` does not solve the problem.

P.S. Currently, building Redis on this VPS could be done in two steps: compile by `clang -c ...` to object files and then linking by launching `strace wasm-ld ...` (yes, I have never succeeded in race winning without strace) several times to win the race:).

**Comment by sunfishcode** [comment]
It's likely that this is [this lld bug](https://bugs.llvm.org/show_bug.cgi?id=41508) which is now [fixed upstream](https://github.com/llvm/llvm-project/commit/5081e41bdae2eb14a3f3eb8810263f9fea8fc7c1). It's not in the 8.0 release, but I've [requested it be included in 8.0.1](https://bugs.llvm.org/show_bug.cgi?id=41602).

**Comment by michaelvoronov** [comment]
Thank you, stack traces are similar, it must be this one.

**Comment by michaelvoronov** [comment]
With the newest llvm this bug isn't reproduced
