### ISSUE TITLE
JS client: add method to fetch a response for the given request

### ISSUE THREAD

**Issue by DieMyst** [fluencelabs/fluence#652]
All requests will be dropped after refreshing a page now. 
And API is not clear for understanding only with `session.resquest().result()`

Add to API methods:
```
session.getResponse("<response-id>")
```
and
```
session.getResponse(request)
```

**Comment by alari** [comment]
@DieMyst should this issue be closed or updated?

**Comment by DieMyst** [comment]
we added polling for a response on the node side. The client API also changed and will look like:
- requestAsync(payload: String): Promise<string>
- request(payload: String): Promise<Result>
- query(requestId: string): Promise<Result>

this task will be done after #774 PR
