### ISSUE TITLE
Smart contract method to query appIDs with storageHashes

### ISSUE THREAD

**Issue by folex** [fluencelabs/fluence#669]
It should return at least `[(appID, storageHash)]`. Maybe also include `storageReceipt`, so it can be used for custom labels on apps.

This is needed in the dashboard to query apps in a single request, and avoid multi-request latency.

**Comment by alari** [comment]
Let's avoid using `storageReceipt` for storing anything except the storage receipt.

Do you consider splitting the smart contract into two (read model, write model) in this issue, so that we could have independent lifecycles for them, or is it planned in a separate issue?

**Comment by folex** [comment]
> Let's avoid using storageReceipt for storing anything except the storage receipt.
OK, but it still makes sense to return `storageReceipt` along with `storageHash`

> is it planned in a separate issue?
I was planning to do that as a separate issue. I thought it exists, but now can't find it. I'll fill it in.

**Comment by alari** [comment]
Do you plan to redeploy the devnet contract for this particular method? Or should the read model be introduced first, and this issue done afterwards?

**Comment by folex** [comment]
Both separation and this issue require to redeploy smart contract, so I'll redeploy after implementing both of them

**Comment by folex** [comment]
Issue for separation is #672
