### ISSUE TITLE
Store last nonce locally in CLI

### ISSUE THREAD

**Issue by folex** [fluencelabs/fluence#675]
Currently, CLI queries Ethereum node for account nonce, and doesn't save it between calls. Because of this, consequent invocations of CLI could result in different transactions with the same nonce, leading to failed transactions.

To avoid that, keep last nonce e.g., config file, or somewhere else on disk, and retrieve next nonce as **maximum** of _ethereum node nonce_ and _local disk nonce_

**Comment by DieMyst** [comment]
There are some problems with the proposed solution. Ethereum transactions may be incomplete. Using nonce from local disk could completely break CLI usage.
