### ISSUE TITLE
Implement timeout on tx send/query in Fluence JS

### ISSUE THREAD

**Issue by folex** [fluencelabs/fluence#678]
Currently, fluence js library keeps query response forever. To save resources, and provide users and developers with familiar behaviour, timeouts should be introduced. 

After a fixed timeout, JS library should stop querying responses and report a failure.

To avoid wasting Fluence network resources, JS clients should implement an exponential backoff timeouts.

**Comment by DieMyst** [comment]
Polling for responses was deleted in #774. Timeouts are presented for HTTP calls and an exponential backoff is used for time of session bans.
The issue could be closed.
