### ISSUE TITLE
Monitor status of the netdata agents

### ISSUE THREAD

**Issue by folex** [fluencelabs/fluence#691]
Currently, node metrics are collected by small netdata agents. Their only job is to collect and send metrics to the central netdata. However, they still exit for different reasons. As it's hard to understand the whole picture of their behaviour, it would be useful to monitor them through Nagios.

Thoughts: there may be some NRPE-like solution that checks that container named `netdata` is running on all nodes.

**Comment by alari** [comment]
@folex isn't it done already?
