### ISSUE TITLE
[fluence-js] unable to compile nor on Node 12 nor on 11

### ISSUE THREAD

**Issue by lcoenen** [fluencelabs/fluence#769]
Hi!

So, I'm trying to integrate Fluence into Next.js, and I get this error when I'm trying to install the library with Node 12.7.0:

    In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:
    ../src/node-boilerplate/inc/scrypt_params_async.h:35:36: error: too few arguments to function call, single argument 'context' was not specified
          maxtime(info[0]->NumberValue()),
                  ~~~~~~~~~~~~~~~~~~~~ ^

(among other, the context error [here](https://gist.github.com/lcoenen/1195185cc5b8fd93eaa69c7165329a75)).

It might because according to [that](https://github.com/fsevents/fsevents/issues/272), fsevents is faulty in version below `1.2.8`. I tried to `yarn add fsevents@1.2.9`, without success.

I also tried to use node 11, but then I get an error in `node_modules/fluence/dist/fluence.js` because of the ES2015 imports (`Unexpected token { at ...`).

Any pointers?

**Comment by folex** [comment]
Please use the [latest Fluence version](https://www.npmjs.com/package/fluence/v/latest) (0.3.4 as of now), it has been updated to be compatible with nextjs. 

Your `next.config.js` should look something like this:
```
const withTM = require('next-transpile-modules');

module.exports = withTM({
    transpileModules: ['fluence']
});
```

`next-transpile-modules` can be found [here](https://www.npmjs.com/package/next-transpile-modules)

**Comment by folex** [comment]
Closing this as resolved, please let me know if that didn't solve your problem
