### ISSUE TITLE
Weird `misc` module

### ISSUE THREAD

**Issue by petar-dambovaliev** [fluencelabs/fluence#992]
[](https://github.com/fluencelabs/fluence/tree/master/trust-graph/src/misc)

There is this weird module that is used only inside `trust-graph` but it exposes it to the outside world at 
https://github.com/fluencelabs/fluence/blob/master/trust-graph/src/lib.rs#L43

Aside from that, i don't think that function itself provides much value.
The name of that module `misc` seems to suggest an anti pattern.
A module should do some useful work and not an amalgamation of random things that have no place elsewhere.

My opinion is that `std::time` should be used directly by the current users of the mod  `misc`.

Let me know your thoughts, cheers.

**Comment by folex** [comment]
Thanks for mentioning it! We've moved the trust graph to a separate repo. We might rename `misc` module there to `time-utils` or alike in some of the refactoring sessions.

I'll close the issue here, consider this noted. Thanks again!
